// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO dream_analysis (analysis_date, dream_count, n_clusters, results_json, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, analysis_date, dream_count, n_clusters, results_json, created_at
`

type CreateAnalysisParams struct {
	AnalysisDate string       `json:"analysis_date"`
	DreamCount   int64        `json:"dream_count"`
	NClusters    int64        `json:"n_clusters"`
	ResultsJson  string       `json:"results_json"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (DreamAnalysis, error) {
	row := q.db.QueryRowContext(ctx, createAnalysis,
		arg.AnalysisDate,
		arg.DreamCount,
		arg.NClusters,
		arg.ResultsJson,
		arg.CreatedAt,
	)
	var i DreamAnalysis
	err := row.Scan(
		&i.ID,
		&i.AnalysisDate,
		&i.DreamCount,
		&i.NClusters,
		&i.ResultsJson,
		&i.CreatedAt,
	)
	return i, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO dream_clusters (analysis_id, cluster_id, dream_count, top_terms, dream_ids, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, analysis_id, cluster_id, dream_count, top_terms, dream_ids, created_at
`

type CreateClusterParams struct {
	AnalysisID int64        `json:"analysis_id"`
	ClusterID  int64        `json:"cluster_id"`
	DreamCount int64        `json:"dream_count"`
	TopTerms   string       `json:"top_terms"`
	DreamIds   string       `json:"dream_ids"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (DreamCluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.AnalysisID,
		arg.ClusterID,
		arg.DreamCount,
		arg.TopTerms,
		arg.DreamIds,
		arg.CreatedAt,
	)
	var i DreamCluster
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.ClusterID,
		&i.DreamCount,
		&i.TopTerms,
		&i.DreamIds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnalysis = `-- name: DeleteAnalysis :exec
DELETE FROM dream_analysis WHERE id = ?
`

func (q *Queries) DeleteAnalysis(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnalysis, id)
	return err
}

const getAnalysisClusters = `-- name: GetAnalysisClusters :many
SELECT id, analysis_id, cluster_id, dream_count, top_terms, dream_ids, created_at
FROM dream_clusters
WHERE analysis_id = ?
ORDER BY cluster_id
`

func (q *Queries) GetAnalysisClusters(ctx context.Context, analysisID int64) ([]DreamCluster, error) {
	rows, err := q.db.QueryContext(ctx, getAnalysisClusters, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DreamCluster{}
	for rows.Next() {
		var i DreamCluster
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.ClusterID,
			&i.DreamCount,
			&i.TopTerms,
			&i.DreamIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAnalysis = `-- name: GetLatestAnalysis :one
SELECT id, analysis_date, dream_count, n_clusters, results_json, created_at
FROM dream_analysis
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAnalysis(ctx context.Context) (DreamAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getLatestAnalysis)
	var i DreamAnalysis
	err := row.Scan(
		&i.ID,
		&i.AnalysisDate,
		&i.DreamCount,
		&i.NClusters,
		&i.ResultsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalysisHistory = `-- name: ListAnalysisHistory :many
SELECT id, analysis_date, dream_count, n_clusters, results_json, created_at
FROM dream_analysis
ORDER BY created_at DESC
`

func (q *Queries) ListAnalysisHistory(ctx context.Context) ([]DreamAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DreamAnalysis{}
	for rows.Next() {
		var i DreamAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisDate,
			&i.DreamCount,
			&i.NClusters,
			&i.ResultsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
