// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dreams.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countDreams = `-- name: CountDreams :one
SELECT COUNT(*) FROM dreams
`

func (q *Queries) CountDreams(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDreams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDream = `-- name: CreateDream :one
INSERT INTO dreams (content, created_at, updated_at)
VALUES (?, ?, ?)
RETURNING id, content, created_at, updated_at
`

type CreateDreamParams struct {
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateDream(ctx context.Context, arg CreateDreamParams) (Dream, error) {
	row := q.db.QueryRowContext(ctx, createDream, arg.Content, arg.CreatedAt, arg.UpdatedAt)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDream = `-- name: DeleteDream :exec
DELETE FROM dreams WHERE id = ?
`

func (q *Queries) DeleteDream(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDream, id)
	return err
}

const getDream = `-- name: GetDream :one
SELECT id, content, created_at, updated_at
FROM dreams
WHERE id = ?
`

func (q *Queries) GetDream(ctx context.Context, id int64) (Dream, error) {
	row := q.db.QueryRowContext(ctx, getDream, id)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomDream = `-- name: GetRandomDream :one
SELECT id, content, created_at, updated_at
FROM dreams
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomDream(ctx context.Context) (Dream, error) {
	row := q.db.QueryRowContext(ctx, getRandomDream)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDreams = `-- name: ListDreams :many
SELECT id, content, created_at, updated_at
FROM dreams
ORDER BY created_at ASC
`

func (q *Queries) ListDreams(ctx context.Context) ([]Dream, error) {
	rows, err := q.db.QueryContext(ctx, listDreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dream{}
	for rows.Next() {
		var i Dream
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDreams = `-- name: SearchDreams :many
SELECT id, content, created_at, updated_at
FROM dreams
WHERE content LIKE '%' || ? || '%'
ORDER BY created_at ASC
`

func (q *Queries) SearchDreams(ctx context.Context, dollar_1 sql.NullString) ([]Dream, error) {
	rows, err := q.db.QueryContext(ctx, searchDreams, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dream{}
	for rows.Next() {
		var i Dream
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDream = `-- name: UpdateDream :one
UPDATE dreams
SET content = ?, updated_at = ?
WHERE id = ?
RETURNING id, content, created_at, updated_at
`

type UpdateDreamParams struct {
	Content   string       `json:"content"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateDream(ctx context.Context, arg UpdateDreamParams) (Dream, error) {
	row := q.db.QueryRowContext(ctx, updateDream, arg.Content, arg.UpdatedAt, arg.ID)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
