// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dreams.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDream = `-- name: CreateDream :one
INSERT INTO dreams (title, content, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, title, content, created_at, updated_at
`

type CreateDreamParams struct {
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateDream(ctx context.Context, arg CreateDreamParams) (Dream, error) {
	row := q.db.QueryRowContext(ctx, createDream,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDream = `-- name: DeleteDream :exec
DELETE FROM dreams WHERE id = ?
`

func (q *Queries) DeleteDream(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDream, id)
	return err
}

const getDream = `-- name: GetDream :one
SELECT id, title, content, created_at, updated_at
FROM dreams
WHERE id = ?
`

func (q *Queries) GetDream(ctx context.Context, id int64) (Dream, error) {
	row := q.db.QueryRowContext(ctx, getDream, id)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDreams = `-- name: ListDreams :many
SELECT id, title, content, created_at, updated_at
FROM dreams
ORDER BY created_at DESC
`

func (q *Queries) ListDreams(ctx context.Context) ([]Dream, error) {
	rows, err := q.db.QueryContext(ctx, listDreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dream{}
	for rows.Next() {
		var i Dream
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDream = `-- name: UpdateDream :one
UPDATE dreams
SET title = ?, content = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, content, created_at, updated_at
`

type UpdateDreamParams struct {
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateDream(ctx context.Context, arg UpdateDreamParams) (Dream, error) {
	row := q.db.QueryRowContext(ctx, updateDream,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Dream
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
