// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Dream struct {
	ID        int64        `json:"id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type DreamAnalysis struct {
	ID           int64        `json:"id"`
	AnalysisDate string       `json:"analysis_date"`
	DreamCount   int64        `json:"dream_count"`
	NClusters    int64        `json:"n_clusters"`
	ResultsJson  string       `json:"results_json"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type DreamCluster struct {
	ID         int64        `json:"id"`
	AnalysisID int64        `json:"analysis_id"`
	ClusterID  int64        `json:"cluster_id"`
	DreamCount int64        `json:"dream_count"`
	TopTerms   string       `json:"top_terms"`
	DreamIds   string       `json:"dream_ids"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type PrimingCache struct {
	ID          int64        `json:"id"`
	Source      string       `json:"source"`
	PayloadJson string       `json:"payload_json"`
	FetchedAt   time.Time    `json:"fetched_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type PrimingContent struct {
	ID        int64          `json:"id"`
	Source    string         `json:"source"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Category  sql.NullString `json:"category"`
	Url       sql.NullString `json:"url"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type PrimingLog struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Source    string    `json:"source"`
	Outcome   string    `json:"outcome"`
	Detail    string    `json:"detail"`
	Content   string    `json:"content"`
}
