// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: priming.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getPrimingCache = `-- name: GetPrimingCache :one
SELECT id, source, payload_json, fetched_at, updated_at
FROM priming_cache
WHERE source = ?
`

func (q *Queries) GetPrimingCache(ctx context.Context, source string) (PrimingCache, error) {
	row := q.db.QueryRowContext(ctx, getPrimingCache, source)
	var i PrimingCache
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.PayloadJson,
		&i.FetchedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrimingLog = `-- name: InsertPrimingLog :exec
INSERT INTO priming_logs (created_at, source, outcome, detail, content)
VALUES (?, ?, ?, ?, ?)
`

type InsertPrimingLogParams struct {
	CreatedAt time.Time `json:"created_at"`
	Source    string    `json:"source"`
	Outcome   string    `json:"outcome"`
	Detail    string    `json:"detail"`
	Content   string    `json:"content"`
}

func (q *Queries) InsertPrimingLog(ctx context.Context, arg InsertPrimingLogParams) error {
	_, err := q.db.ExecContext(ctx, insertPrimingLog,
		arg.CreatedAt,
		arg.Source,
		arg.Outcome,
		arg.Detail,
		arg.Content,
	)
	return err
}

const listPrimingLogs = `-- name: ListPrimingLogs :many
SELECT id, created_at, source, outcome, detail, content
FROM priming_logs
ORDER BY created_at DESC
`

func (q *Queries) ListPrimingLogs(ctx context.Context) ([]PrimingLog, error) {
	rows, err := q.db.QueryContext(ctx, listPrimingLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrimingLog{}
	for rows.Next() {
		var i PrimingLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Source,
			&i.Outcome,
			&i.Detail,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrimingCache = `-- name: UpsertPrimingCache :exec
INSERT INTO priming_cache (source, payload_json, fetched_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source) DO UPDATE SET
  payload_json = excluded.payload_json,
  fetched_at = excluded.fetched_at,
  updated_at = excluded.updated_at
`

type UpsertPrimingCacheParams struct {
	Source      string       `json:"source"`
	PayloadJson string       `json:"payload_json"`
	FetchedAt   time.Time    `json:"fetched_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpsertPrimingCache(ctx context.Context, arg UpsertPrimingCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrimingCache,
		arg.Source,
		arg.PayloadJson,
		arg.FetchedAt,
		arg.UpdatedAt,
	)
	return err
}
